language: objective-c
before_install: 
    - export LANG=en_US.UTF-8
    - rake install
script: 
    - rake clean:tests
    - rake test
    - rake analyze
notifications:
    email:
        recipients:
         - amcknight@twitter.com
         - mmassicotte@twitter.com
        on_success: change
        on_failure: always